### ISSUE TITLE
Unpacking variable-length structs into array

### ISSUE THREAD

**Issue by mpictor** [go-restruct/restruct#49]
I have a data stream containing an unknown number of variable-length structs.

I want to do something like

```go
	type someStruct struct {
		Size    uint8 `struct:"sizeof=Payload"`
		Payload []byte
	}
	buf:=[]byte{/*...*/}
	var list []someStruct
	//list := make([]someStruct, 20) //also tried this, still fails
	err := restruct.Unpack(buf, binary.LittleEndian, &list)
	if err != nil {
            //...
        }
        fmt.Println(len(list)) //always 0
```
but that doesn't work. Instead I have to track the size of each struct and iterate until the buffer is empty.
```go
	type someStruct struct {
		Size    uint8 `struct:"sizeof=Payload"`
		Payload []byte
	}
	buf:=[]byte{/*...*/}
	var list []someStruct
	var s someStruct
	var idx int
	for idx < len(buf) {
		err := restruct.Unpack(buf[idx:], binary.LittleEndian, &s)
		if err != nil {
			//...
		}
		idx += int(s.Size) + 1
		list = append(list, s)
	}
        fmt.Println(len(list)) //non-zero, as desired
```
It seems like this would be a common use case; is there no way to do it without tracking position in the buffer and iterating until it's done?

**Comment by mpictor** [comment]
Looks like the answer is to enable expressions and use something like
```golang
type Records struct {
	List []Record `struct-while:"!_eof"`
}
```

Now... what about null-terminated strings? I tried several different things, no luck.

```golang
type NullTerm1 struct{
    //...
    Name string //thought maybe it would automatically stop on null, but no
    //...
}
type NullTerm2 struct{
    //...
    Name string `struct:"[]byte" struct-while:"!nil"` //also struct-while:"!0"
    //...
}
```

**Comment by jchv** [comment]
Apologies for the lack of a response. I've been a bit busy with real life stuff :(

Yes, you have found the most reasonable option for consuming an unbounded array of records.

As far as null-terminated strings go, restruct should provide one. However, it is possible to construct one, and you can see this done in one of the tests: https://github.com/go-restruct/restruct/blob/983b86fa188e1ffdd74140a42afc3543285fc98d/packing_test.go#L731

Once again, I do apologize for coming into this late. If you need more help feel free to reply here or create a new issue. I'll leave this issue open for now.

**Comment by mpictor** [comment]
No worries :)

Thanks for the pointer to `type CString`, I'd been meaning to look into pack/unpack methods.

I'm guessing #2 (code gen) is a long way off? I'd be happy to see that functionality, but I'm not sure where to start.

**Comment by jchv** [comment]
I had made some attempts, but despite seeming fairly straightforward in theory, it definitely is tricky due to just how different the two runtimes are. I think it would warrant consideration for a full rewrite of restruct that uses an intermediate in-memory structure that can either just-in-time perform packing or unpacking, or do code generation. The expression runtime also needs to be adjusted; initially it could remain JIT’d, but it would be vastly superior to support compiling the expressions to Go code and being able to optimize common patterns.

Despite a couple of attempts, though, I never was really that satisfied by any of them. Expressions also took a few attempts to get right, but this has even more implications than that did.
