### ISSUE TITLE
[FEATURE] "cstring" type and success count in parsing functions

### ISSUE THREAD

**Issue by 5IGI0** [go-restruct/restruct#59]
i would like to request the addition of a ``cstring`` type to the parsing functions. \
Currently, there is no way to parse C-strings (strings terminated by a nullbyte) in the library (am i wrong?), \
which can be time-consuming and error-prone for developers who need to parse such strings.

The addition of a cstring type to the parsing functions would make it easier for developers to parse C-strings without having to write their own parsing functions.

In addition, it would be helpful to have a success count returned by the parsing functions, similar to the scanf function in C. \
This would enable developers to easily manage multiple versions of their code by parsing only the fields that are present in a particular version, while ignoring the fields that are not present.

```go
type JoinPacket struct {
	PacketVersion	uint8		`struct:"uint8"`
	Username	string		`struct:"cstring"`
	ClientVersion	uint32		`struct:"uint32"`
	AuthToken	[16]byte	`struct:"[16]byte"` // added in a newer version so can be ignored if an older version is joining
}
```

Overall, I believe that the addition of a `cstring` type and success count in parsing functions would greatly benefit developers.
Thank you for considering this feature request.

**Comment by jchv** [comment]
A custom pack/unpack implementation can be used. Take a look at this example type:
https://github.com/go-restruct/restruct/blob/1bb20937bae4323212206089007dfebc305d90d1/packing_test.go#L732

**Comment by 5IGI0** [comment]
My bad, i should have paid a bit more attention :'(
also, is there any way to find out if there are any remaining data and/or to know the number of fields that have been parsed?

**Comment by jchv** [comment]
Not a problem. Unfortunately there's not a good way to know how many bytes are read, that's just a design flaw in restruct v1. However, you can call `restruct.SizeOf` on your struct to determine how large it is in bytes, which you could then use to figure out how many bytes were read, since it will in fact reflect the size of dynamic structures as long as you pass in the struct you just unpacked to. You could also use the beta expressions feature to do more interesting things directly in the struct with "excess" data, like reading into a slice until EOF.

**Comment by 5IGI0** [comment]
thank you for your help and wish you a good day
